

GET http://localhost:5000/api//projects/JohnDoe13/follow`  HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG5Eb2UxMCIsImlhdCI6MTY1MDU2ODAzNH0.gIVJXy3Vd0aPzlOFSY6Xe05xJ5E033tvUTKgHn8ABHc